version: "3"
services:
  client:
    build:
      context: ./
    volumes:
      - ./content:/app/content
      - ./src:/app/src
    ports:
      - "8000:8000"
    dns:
      - 192.168.88.1
      - 8.8.8.8
      - 8.8.4.4
